[build]
  publish = "client/build"
  command = "cd client && npm run build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "client/build"
