services:
  - type: web
    name: ecommerce-website
    env: node
    plan: free
    buildCommand: npm run install-client && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
